routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/**
 * Restricted to users with the show-dayinc permission.
 */
Route::resource('dayincs', 'DayincController')->middleware('can:show-dayinc');

/**
 * For all logged in users
 */
Route::resource('warehouses', 'WarehouseController')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

resources/views/warehouses/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="pull-left">
            <h2>Add New Warehouse</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('warehouses.index') }}"> Back</a>
        </div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('warehouses.store') }}" method="POST">
    @csrf
  
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Warehouse Name:</strong>
                <input type="text" name="name" class="form-control" placeholder="Please type the name of the warehouse">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Warehouse Code:</strong>
                <input type="text" name="code" class="form-control" placeholder="Please type the name of the warehouse">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</form>
</div></div>
@endsection

resources/views/warehouses/edit.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="pull-left">
                <h2>Edit Dayinc</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('warehouses.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('warehouses.update',$warehouse->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-group">
                    <strong>Code:</strong>
                    <input type="text" name="code" value="{{ $warehouse->code }}" class="form-control" placeholder="Warehouse Code">
                </div>
            </div>
	    </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-group">
                    <strong>Code:</strong>
                    <input type="text" name="name" value="{{ $warehouse->name }}" class="form-control" placeholder="Warehouse Name">
                </div>
            </div>
	    </div>

        <div class="row justify-content-center">
        <div class="col-md-8">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        </div>
    </form>
</div></div>
@endsection

resources/views/warehouses/index.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="pull-left">
                <h2>Warehouses</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('warehouses.create') }}"> Create New Warehouse</a>
            </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
  </div></div>
  <div class="row justify-content-center">
        <div class="col-md-8">
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Code</th>
	        <th>Name</th>
	        <th width="280px">Action</th>
        </tr>
        @foreach ($warehouses as $warehouse)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $warehouse->code }}</td>
            <td>{{ $warehouse->name }}</td>
            <td>
                <form action="{{ route('warehouses.destroy',$warehouse->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('warehouses.show',$warehouse->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('warehouses.edit',$warehouse->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $warehouses->links() !!}
</div>      
    </div>
@endsection

resources/views/warehouses/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="pull-left">
                <h2>Show Dayinc</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('warehouses.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Code:</strong>
                {{ $warehouse->code }}
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $warehouse->name }}
            </div>
        </div>
    </div>

@endsection