routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

/**
 * Restricted to users with the show-dayinc permission.
 */
Route::resource('dayincs', 'DayincController')->middleware('can:show-dayinc');

/**
 * For all logged in users
 */
Route::resource('warehouses', 'WarehouseController')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes(['register' => false]);

app/Dayinc.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Dayinc extends Model
{
     protected $fillable = [
	     'shiftday',
	     'shiftnumber',
	     'salesperson',
	     'cashstart',
	     'cashend',
	     'cashtotal',
	     'gst',
	     'totalincgst',
	     'totalexclgst',
	     'card',
	     'banked',
	     'comment',
    ];
}

app/Http/Controllers/DayincController.php
<?php

namespace App\Http\Controllers;

use App\Dayinc;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;

class DayincController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {         
       $dayincs = Dayinc::latest()->paginate(7);
        return view('dayincs.index',compact('dayincs'))
            ->with('i', (request()->input('page', 1) - 1) * 5); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
                return view('dayincs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'shiftday' => 'required',
            'shiftnumber' => 'required',
        ]);
  	$this->updateTotals($request);
 print_r($request->all()); 
        Dayinc::create($request->all());
   
        return redirect()->route('dayincs.index')
                        ->with('success','Dayinc created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Dayinc  $dayinc
     * @return \Illuminate\Http\Response
     */
    public function show(Dayinc $dayinc)
    {
               return view('dayincs.show',compact('dayinc'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Dayinc  $dayinc
     * @return \Illuminate\Http\Response
     */
    public function edit(Dayinc $dayinc)
    {
               return view('dayincs.edit',compact('dayinc'));
 
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Dayinc  $dayinc
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dayinc $dayinc)
    {
       $request->validate([
            'shiftday' => 'required',
            'shiftnumber' => 'required',
    ]);
  	$this->updateTotals($request);
        $dayinc->update($request->all());
  
        return redirect()->route('dayincs.index')
                        ->with('success','Dayinc updated successfully'); 
    }

    private function updateTotals(&$request) 
    {
	    $cashstart = $request->input('cashstart');
	    $cashend = $request->input('cashend');
	    $card = $request->input('card');
	    echo 'start: ' . $cashstart;
	    $cash = null;
	    if (!empty($cashstart) && !empty($cashend) && $cashend*1 > 0) {
		    $cash = $cashend - $cashstart;
	    }

	    if ($cash !== null) {
		    $request->request->add(['cashtotal' => $cash]);
	    }
	    if ($cash !== null && $card !== null) {
		    $totalinclgst = round($cash + $card, 2);
		    $totalexclgst = round($totalinclgst/1.15, 2);
		    $gst = round($totalinclgst-$totalexclgst);
	    	    $request->request->add(['totalincgst' => $totalinclgst]);
		    $request->request->add(['gst' => $gst]);
		    $request->request->add(['totalexclgst' => $totalexclgst]);
	    }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Dayinc  $dayinc
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dayinc $dayinc)
    {
	  $dayinc->delete();
  
        return redirect()->route('dayincs.index')
                        ->with('success','Dayinc deleted successfully');
    }
}

resources/views/dayincs/create.blade.php
@extends('layouts.app')
  
@section('content')
<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="pull-left">
            <h2>Add New Dayinc</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('dayincs.index') }}"> Back</a>
        </div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('dayincs.store') }}" method="POST">
    @csrf
  
     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Shiftday:</strong>
                <input type="date" name="shiftday" class="form-control" value="{{ date('Y-m-d') }}">
            </div>
	</div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Shift # of the day:</strong>
                <input type="number" name="shiftnumber" class="form-control" value="1">
            </div>
	</div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Sales person (you):</strong>
                <input type="text" name="salesperson" class="form-control" placeholder="Please type your name">
            </div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Cash at the beginning of the shift:</strong>
                <input type="number" name="cashstart" step="any" class="form-control" placeholder="90.00">
            </div>
        </div>
	<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Cash at the end of the shift:</strong>
                <input type="number" name="cashend" step="any" class="form-control" placeholder="144.00">
            </div>
        </div>
	<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Card sales:</strong>
                <input type="number" name="card" step="any" class="form-control" placeholder="133.11">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Comments:</strong>
                <textarea class="form-control" style="height:150px" name="comment" placeholder="Detail"></textarea>
            </div>
	</div>
	<div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Paid into bank account after shift:</strong>
                <input type="number" step="any" name="banked" class="form-control" placeholder="133.11">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
   
</form>
</div></div>
@endsection

resources/views/dayincs/edit.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="pull-left">
                <h2>Edit Dayinc</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('dayincs.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('dayincs.update',$dayinc->id) }}" method="POST">
        @csrf
        @method('PUT')
   
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-group">
                    <strong>Shiftday:</strong>
                    <input type="text" name="shiftday" value="{{ $dayinc->shiftday }}" class="form-control" placeholder="Name">
                </div>
            </div>
	    </div>
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="form-group">
                    <strong>Shift # of the day:</strong>
                    <input type="number" name="shiftnumber" value="{{ $dayinc->shiftnumber }}" class="form-control" value="1">
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Sales person (you):</strong>
                <input type="text" name="salesperson" value="{{ $dayinc->salesperson }}" class="form-control" placeholder="Please type your name">
            </div>
        </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Cash at the beginning of the shift:</strong>
                <input type="number" name="cashstart" value="{{ $dayinc->cashstart }}" step="any" class="form-control" placeholder="">
            </div>
        </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Cash at the end of the shift:</strong>
                <input type="number" name="cashend" value="{{ $dayinc->cashend }}" step="any" class="form-control" placeholder="">
            </div>
        </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Card sales:</strong>
                <input type="number" name="card" value="{{ $dayinc->card }}" step="any" class="form-control" placeholder="133.11">
            </div>
        </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Comments:</strong>
                <textarea class="form-control" style="height:150px" name="comment" placeholder="">{{ $dayinc->comment }}</textarea>
            </div>
        </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Paid into bank account after shift:</strong>
                <input type="number" name="banked" value="{{ $dayinc->banked }}" step="any" class="form-control" placeholder="">
            </div>
        </div>
        </div>
        <div class="row justify-content-center">
        <div class="col-md-8">
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        </div>
    </form>
</div></div>
@endsection

resources/views/dayincs/index.blade.php
@extends('layouts.app')
 
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="pull-left">
                <h2>Test App</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('dayincs.create') }}"> Create New Dayinc</a>
            </div>
   
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
  </div></div>
  <div class="row justify-content-center">
        <div class="col-md-8">
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Shiftday</th>
	    <th>Shift#</th>
	    <th>Cash</th>
	    <th>Card</th>
	    <th>Total</th>
            <th width="280px">Action</th>
        </tr>
        @foreach ($dayincs as $dayinc)
        <tr>
            <td>{{ ++$i }}</td>
            <td>{{ $dayinc->shiftday }}</td>
	    <td>{{ $dayinc->shiftnumber }}</td>
	    <td>{{ $dayinc->cashtotal }}</td>
	    <td>{{ $dayinc->card }}</td>
	    <td>{{ $dayinc->totalexclgst }}</td>
            <td>
                <form action="{{ route('dayincs.destroy',$dayinc->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('dayincs.show',$dayinc->id) }}">Show</a>
    
                    <a class="btn btn-primary" href="{{ route('dayincs.edit',$dayinc->id) }}">Edit</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
    {!! $dayincs->links() !!}
</div>      
    </div>
@endsection

resources/views/dayincs/layout.blade.php
@extends('layouts.app')  

@section('content')
<div class="container">
    @yield('content')
</div>
   

resources/views/dayincs/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="pull-left">
                <h2>Show Dayinc</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('dayincs.index') }}"> Back</a>
            </div>
        </div>
    </div>
   
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="form-group">
                <strong>Shiftday:</strong>
                {{ $dayinc->shiftday }}
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Shift #:</strong>
                {{ $dayinc->shiftnumber }}
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Sales Person:</strong>
                {{ $dayinc->salesperson }}
            </div>
        </div>
        <div class="col-md-8">
	    <div class="form-group">
		<table>
		<tr><td>Cash before shift</td><td>{{ $dayinc->cashstart }}</td></tr>
		<tr><td>Cash after shift</td><td>{{ $dayinc->cashend }}</td></tr>
		<tr><td>Cash total</td><td>{{ $dayinc->cashtotal }}</td></tr>
		<tr><td>Card total</td><td>{{ $dayinc->card }}</td></tr>
		<tr><td>Total incl. gst</td><td>{{ $dayinc->totalincgst }}</td></tr>
		<tr><td>GST</td><td>{{ $dayinc->gst }}</td></tr>
		<tr><td>Total excl. gst</td><td>{{ $dayinc->totalexclgst }}</td></tr>
		</table>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Paid into bank account after day:</strong>
                {{ $dayinc->banked }}
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <strong>Comment:</strong>
                {{ $dayinc->comment }}
            </div>
        </div>
    </div>
</div></div>
@endsection